#!/bin/bash


# ------------------------------------------------------------------------------
# Intial Configurations
# ------------------------------------------------------------------------------
set -e

# Use qubes-builder directory as base
if [ "$(basename $PWD)" == "scripts-debian" ]; then
    pushd ..
    trap "popd" EXIT
fi

# Default Distribution
if [ -z "$DISTS_VM" ]; then
    DISTS_VM=wheezy
fi
echo "DISTS_VM set to: $BASE"

# Get absolute path of directory
DIR="$(readlink -m .)"

# Whonix Directory
export WHONIX_DIR="$(readlink -m ./qubes-src/Whonix)"

if [ -z "$BUILDERCONF" ]; then
    export BUILDERCONF="example-configs/debian.conf"
fi
echo "BUILDERCONF set to: ${BUILDERCONF}"

if ! [ -f "$BUILDERCONF" ]; then
    echo "Can not find ${BUILDERCONF}. Exiting..."
    exit 1
fi

# Source umount function
. ./scripts-debian/umount_kill.sh

# ==============================================================================
# FUNCTIONS
# ==============================================================================

# ------------------------------------------------------------------------------
# Set Whonix TEMPALTE_FLAVOR
# ------------------------------------------------------------------------------
set_whonix_version() {
    # If whonix version is not passed; only a debian package will be built
    [ "$1" ] && WHONIX_VERSION=$1 || WHONIX_VERSION=
    echo "TEMPLATE_FLAVOR is: $WHONIX_VERSION"
}


# ==============================================================================
# debian-install execution options
# ==============================================================================


# ------------------------------------------------------------------------------
# debian-install clean-all
#
# Clean All (deletes everything in qubes-src as well; USE WITH CAUTION)
# *** commit and push any gits you worked on ***
# ------------------------------------------------------------------------------
if [ "$1" == "clean-all" ] ; then
    make clean-all || true
fi


# ------------------------------------------------------------------------------
# debian-install clean
#
# Clean - Basic clean removes all source and compiled images
# ------------------------------------------------------------------------------
if [ "$1" == "clean" ] ; then
    make clean-most || true
fi


# ------------------------------------------------------------------------------
# debian-install sources
#
# Get all sources to build project, including Whonix sources and my test repos
# ------------------------------------------------------------------------------
if [ "$1" == "sources" ] ; then
    make get-sources
fi


# ------------------------------------------------------------------------------
# debian-install build
#
# Build all quebes packages for chosen distribution
# Templates are built within a seperate step
# ------------------------------------------------------------------------------
if [ "$1" == "build" ] ; then
    make build
fi


# ------------------------------------------------------------------------------
# debian-install template
# debian-install template whonix-gateway
# debian-install template whonix-workstation
#
# Builds an installable rpm package for distribution or distribution +
# TEMPLATE_FLAVOR (whonix-gateway, whonix-workstation)
#
# Should continue building tempalte where it left off in case of build errors
# ------------------------------------------------------------------------------
if [ "$1" == "template" ] ; then
    set_whonix_version $2
    DISTS_VM=$DISTS_VM TEMPLATE_FLAVOR=$WHONIX_VERSION make template
fi


# ------------------------------------------------------------------------------
# debian-install template-update
# debian-install template-update whonix-gateway
# debian-install template-update whonix-workstation
#
# Updates the tempate (will re-run all qubize steps)
# XXX: May attempt to re-install Whonix again as well
# ------------------------------------------------------------------------------
if [ "$1" == "template-update" ] ; then
    set_whonix_version $2
    #TEMPLATE_FLAVOR=$WHONIX_VERSION UPDATE=true make linux-template-builder
    DISTS_VM=$DISTS_VM TEMPLATE_FLAVOR=$WHONIX_VERSION UPDATE=true make template-update
fi
