include:
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-base.yml'

prep:sources:
  extends: .components_prepare
  before_script:
    - cp -a $CI_PROJECT_DIR ~/qubes-builder
    - git clone https://github.com/QubesOS/qubes-continuous-integration ~/qubes-continuous-integration
    - mv ~/qubes-continuous-integration/scripts/* ~/qubes-builder/scripts/
  variables:
    COMPONENTS: "core-vchan-xen builder-rpm"

# just any component build test
tests:vm-fc32:no-upstream-tarball:
  extends: .components_build
  stage: tests
  needs:
    - prep:sources
    - project: QubesOS/qubes-builder-rpm
      ref: master
      job: chroot:vm-fc32
      artifacts: true
  tags:
    - docker
  variables:
    DISTS_VM: fc32
    USE_QUBES_REPO_VERSION: "4.1"
    USE_QUBES_REPO_TESTING: "1"
    USE_DIST_BUILD_TOOL: 1
    COMPONENTS: core-vchan-xen
  script:
    - ~/qubes-builder/scripts/gitlab-build "$COMPONENTS"
    - ls -l ~/qubes-builder/qubes-packages-mirror-repo/vm-fc32/rpm/*vchan*rpm

tests:sources-unsigned:
  extends: .components_prepare
  before_script:
    - cp -a $CI_PROJECT_DIR ~/qubes-builder
  script:
   - "! ~/qubes-builder/scripts/gitlab-prepare \"$COMPONENTS\""
  variables:
    # this does not have signed tags
    COMPONENTS: updates-status
    GIT_URL_updates_status: https://github.com/QubesOS/updates-status

tests:sources-unknown-key:
  extends: .components_prepare
  before_script:
    - cp -a $CI_PROJECT_DIR ~/qubes-builder
  script:
   - "! ~/qubes-builder/scripts/gitlab-prepare \"$COMPONENTS\""
  variables:
    # this is signed with non-code key
    COMPONENTS: doc


prep:non-fast-clone:
  extends: .components_prepare
  before_script:
    - cp -a $CI_PROJECT_DIR ~/qubes-builder
    - git clone https://github.com/QubesOS/qubes-continuous-integration ~/qubes-continuous-integration
    - mv ~/qubes-continuous-integration/scripts/* ~/qubes-builder/scripts/
  variables:
    GIT_CLONE_FAST: ""
    COMPONENTS: "core-vchan-xen builder-rpm"

### FULL BUILD

## SOURCES

sources:r4.1:
  extends: .fullbuild_sources_job
  variables:
    RELEASE: "4.1"

## COMPONENTS

build:r4.1-vm-bullseye:
  extends: .fullbuild_components_job
  needs:
    - sources:r4.1
  variables:
    RELEASE: "4.1"
    DISTS_VM: bullseye

build:r4.1-vm-fc33:
  extends: .fullbuild_components_job
  needs:
    - sources:r4.1
  variables:
    RELEASE: "4.1"
    DISTS_VM: fc33

build:r4.1-vm-fc34:
  extends: .fullbuild_components_job
  needs:
    - sources:r4.1
  variables:
    RELEASE: "4.1"
    DISTS_VM: fc34

build:r4.1-vm-centos8:
  extends: .fullbuild_components_job
  needs:
    - sources:r4.1
  variables:
    RELEASE: "4.1"
    DISTS_VM: centos8

build:r4.1-vm-archlinux:
  extends: .fullbuild_components_job
  needs:
    - sources:r4.1
  variables:
    RELEASE: "4.1"
    DISTS_VM: archlinux

## TEMPLATES

tmpl:r4.1-vm-bullseye:
  extends: .fullbuild_template_job
  needs:
    - sources:r4.1
    - build:r4.1-vm-bullseye
  variables:
    RELEASE: "4.1"
    DISTS_VM: bullseye

tmpl:r4.1-vm-fc33:
  extends: .fullbuild_template_job
  needs:
    - sources:r4.1
    - build:r4.1-vm-fc33
  variables:
    RELEASE: "4.1"
    DISTS_VM: fc33

tmpl:r4.1-vm-fc34:
  extends: .fullbuild_template_job
  needs:
    - sources:r4.1
    - build:r4.1-vm-fc34
  variables:
    RELEASE: "4.1"
    DISTS_VM: fc34

tmpl:r4.1-vm-centos8:
  extends: .fullbuild_template_job
  needs:
    - sources:r4.1
    - build:r4.1-vm-centos8
  variables:
    RELEASE: "4.1"
    DISTS_VM: centos8

tmpl:r4.1-vm-archlinux:
  extends: .fullbuild_template_job
  needs:
    - sources:r4.1
    - build:r4.1-vm-archlinux
  variables:
    RELEASE: "4.1"
    DISTS_VM: archlinux
