#!/bin/sh

DIR=$1
DISTRO=$2
if [ -n "$3" ]; then
    PKGLISTFILE="$3"
else
    PKGLISTFILE="build-pkgs-base.list"
fi

YUM_OPTS="$YUM_OPTS -x kernel"

set -e
if [ "$VERBOSE" -ge 2 -o "$DEBUG" == "1" ]; then
    set -x
else
    YUM_OPTS="$YUM_OPTS -q"
fi

INITIAL=

if ! [ -d $DIR/home/user ]; then
    INITIAL=1
    mkdir -p $DIR

    echo "-> Initializing RPM database..."
    rpm --initdb --root=$DIR
    rpm --import --root=$DIR keys_$DISTRO/*

    echo "-> Installing core RPM packages..."
    rpm -i --root=$DIR base_rpms_$DISTRO/*.rpm

    # Always install at least base pkgs
    yum install -c $PWD/yum.conf -y $YUM_OPTS --installroot=$DIR `cat build-pkgs-base.list`

    [ -n "$SUDO_UID" ] && USER_OPTS="-u $SUDO_UID"
    [ -n "$USER_UID" ] && USER_OPTS="-u $USER_UID"
    if [ -n "$USER_GID" ]; then
        chroot $DIR groupadd -g $USER_GID user
    elif [ -n "$SUDO_GID" ]; then
        chroot $DIR groupadd -g $SUDO_GID user
    else
        chroot $DIR groupadd user
    fi
    chroot $DIR sh -c "cd dev; /sbin/MAKEDEV generic loop;useradd -g user $USER_OPTS -m user;su -c 'mkdir qubes-src' - user"
    # Just to be sure that RPMDB has right format (eg when building host is newer than FC13)
    chroot $DIR rpm --rebuilddb 2> /dev/null
fi
./update-local-repo.sh $DISTRO
cp repos_$DISTRO/*.repo $DIR/etc/yum.repos.d/
sed -i -e "s#ROOT#$PWD#" $DIR/etc/yum.repos.d/*-local.repo

if ! [ -r $DIR/proc/cpuinfo ]; then
    mount -t proc proc $DIR/proc
fi

if ! [ -d $DIR/tmp/qubes-rpms-mirror-repo/rpm ]; then
    mkdir -p $DIR/tmp/qubes-rpms-mirror-repo
    mount --bind $PWD/qubes-rpms-mirror-repo/$DISTRO $DIR/tmp/qubes-rpms-mirror-repo
fi
cp /etc/resolv.conf $DIR/etc/
# some packages assumes existence of this file
touch $DIR/etc/fstab

PKGGROUPS="$(cat $PKGLISTFILE)"
echo "-> Installing package groups..."
chroot $DIR yum install -y $YUM_OPTS $PKGGROUPS
