#!/bin/sh
# vim: set ts=4 sw=4 sts=4 et :

DIR=$1
DISTRO=$2
if [ -n "$3" ]; then
    PKGLISTFILE="$3"
else
    PKGLISTFILE="build-pkgs-base.list"
fi

set -e
if [ "$VERBOSE" -ge 2 -o "$DEBUG" == "1" ]; then
    set -x
else
    YUM_OPTS="$YUM_OPTS -q"
fi

INITIAL=

if ! [ -d $DIR/home/user ]; then
    INITIAL=1
    mkdir -p $DIR

    echo "-> Initializing RPM database..."
    rpm --initdb --root=$DIR
    rpm --import --root=$DIR keys_$DISTRO/*

    if [ "$DISTRO" == "fc21" ]; then
        echo "-> Retreiving core RPM packages..."
        INITIAL_PACKAGES="filesystem setup fedora-release"

        yum --disablerepo=\* --enablerepo=fedora -y --installroot="${DIR}" --releasever=${DISTRO/fc/} install --downloadonly --downloaddir="base_rpms_${DISTRO}" ${INITIAL_PACKAGES}

        for file in base_rpms_${DISTRO}/*; do
            result=$(rpm --root=$DIR --checksig "${file}") || {
                echo "Filename: ${file} failed verification.  Exiting!"
                exit 1
            }
            result_status="${result##*:}"
            echo "${result_status}" | grep -q 'PGP' && {
                echo "Filename: ${file} contains an invalid PGP signature.  Exiting!"
                exit 1
            }
            echo "${result_status}" | grep -q 'pgp' || {
                echo "Filename: ${file} is not signed.  Exiting!"
                exit 1
            }
        done
    fi

    echo "-> Installing core RPM packages..."
    rpm -i --root=$DIR base_rpms_$DISTRO/*.rpm

    # Always install at least base pkgs
    yum install -c $PWD/yum.conf -y $YUM_OPTS --installroot=$DIR `cat build-pkgs-base.list`

    [ -n "$SUDO_UID" ] && USER_OPTS="-u $SUDO_UID"
    [ -n "$USER_UID" ] && USER_OPTS="-u $USER_UID"
    if [ -n "$USER_GID" ]; then
        chroot $DIR groupadd -g $USER_GID user
    elif [ -n "$SUDO_GID" ]; then
        chroot $DIR groupadd -g $SUDO_GID user
    else
        chroot $DIR groupadd user
    fi
    # fc20 setup doesn't include uucp group, which would cause MAKEDEV failure
    chroot $DIR groupadd -rf uucp
    chroot $DIR sh -c "cd dev; /sbin/MAKEDEV generic loop;useradd -g user $USER_OPTS -m user;su -c 'mkdir qubes-src' - user"
    # Just to be sure that RPMDB has right format (eg when building host is newer than FC13)
    chroot $DIR rpm --rebuilddb 2> /dev/null
else
    # update chroot
    chroot $DIR groupadd -rf uucp 2>/dev/null || :
    chroot $DIR sh -c "cd dev; /sbin/MAKEDEV generic loop"
fi
./update-local-repo.sh $DISTRO
cp repos_$DISTRO/*.repo $DIR/etc/yum.repos.d/
sed -i -e "s#ROOT#$PWD#" $DIR/etc/yum.repos.d/*-local.repo

if ! [ -r $DIR/proc/cpuinfo ]; then
    mount -t proc proc $DIR/proc
fi

if ! [ -d $DIR/tmp/qubes-rpms-mirror-repo/rpm ]; then
    mkdir -p $DIR/tmp/qubes-rpms-mirror-repo
    mount --bind $PWD/qubes-rpms-mirror-repo/$DISTRO $DIR/tmp/qubes-rpms-mirror-repo
fi
cp /etc/resolv.conf $DIR/etc/
# some packages assumes existence of this file
touch $DIR/etc/fstab

PKGGROUPS="$(cat $PKGLISTFILE)"
echo "-> Installing package groups..."
chroot $DIR yum install -y $YUM_OPTS $PKGGROUPS
