#!/bin/bash

set -e
[ "$DEBUG" = "1" ] && set -x

TAR_VERSION="$(tar --version | head -1 | awk '{print $4}')"

GIT_ARCHIVE_SRC="$(readlink -f "$1")"
GIT_TARBALL_NAME="${2%.gz}"
GIT_ARCHIVE_PREFIX="$3"

# We enter in the qubes source component
pushd "$GIT_ARCHIVE_SRC"

# Define SOURCE_DATE_EPOCH from git latest commit timestamp
SOURCE_DATE_EPOCH=$(git log -1 --format=%ct)

# Create the archive:
# - based on https://reproducible-builds.org/docs/archives/
# - excluding .git, pkgs folder and prevent probable not so
#   clever implementation of 'tar' which would result in
#   an infinity loop due to tar '.'

if [ "$(printf '%s\n' "$TAR_VERSION" "1.28" | sort -V | head -n1)" == "1.28" ]; then
    tar --sort=name \
        --mtime="@${SOURCE_DATE_EPOCH}" \
        --owner=0 --group=0 --numeric-owner \
        --xform="s%^\./%${GIT_ARCHIVE_PREFIX}%" \
        --exclude-vcs-ignores \
        --exclude pkgs --exclude '.git*' --exclude "${GIT_TARBALL_NAME}" \
        -cf "${GIT_TARBALL_NAME}" .
else
    find . -not -path './.git*' -not -path './pkgs*' -print0 | LC_ALL=C sort -z |
    tar --no-recursion --null -T - \
        --mtime="@${SOURCE_DATE_EPOCH}" \
        --owner=0 --group=0 --numeric-owner \
        --xform="s%^\./%${GIT_ARCHIVE_PREFIX}%" \
        --exclude "${GIT_TARBALL_NAME}" \
        -cf "${GIT_TARBALL_NAME}"
fi

gzip -fn "${GIT_TARBALL_NAME}"

popd
