#!/bin/bash

set -ex

# go to builder main directory
cd "$(dirname $0)/.."

# clean env only one chroot
chroot_dir="$(ls -d chroot-* || :)"
if [ -z "$chroot_dir" ]; then
    echo "Nothing was built, skipping install"
    exit
fi
YUM="$(sudo chroot "$chroot_dir" /usr/bin/which dnf || true)"
if [ -z "$YUM" ]; then
    YUM="$(sudo chroot "$chroot_dir" /usr/bin/which yum || true)"
fi

APT="$(sudo chroot "$chroot_dir" /usr/bin/which apt-get || true)"
if [ "$APT" ]; then
    APT_ENV="DEBIAN_FRONTEND=noninteractive DEBCONF_NOWARNINGS=yes DEBIAN_PRIORITY=critical"
    APT_OPTS="-o Dpkg::Options::=--force-confnew --yes"

    # install reprotest and devscripts
    sudo chroot "$chroot_dir" bash -c -l "$APT_ENV apt-get $APT_OPTS install reprotest devscripts"
    CONTROLS="$(sudo chroot "$chroot_dir" bash -c -l 'find /tmp/qubes-deb -type f -name "*.dsc"')"

    for control in $CONTROLS
    do
        # install all dependencies first
        sudo chroot "$chroot_dir" bash -c -l "mk-build-deps -i --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' $control"

        # reprotest
        sudo chroot "$chroot_dir" bash -c -l "reprotest $control"
    done
fi
